apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: pg-secure-audit
    type: postgres
    access: proxy
    url: postgres:5432
    database: auditdb
    user: audit
    secureJsonData:
      password: auditpass
    jsonData:
      database: auditdb
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
